# Generated by Django 5.1.2 on 2024-10-14 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_quote', '0004_tag_remove_quote_tags_quote_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
